version: '3.6'
services: 
  kodi:
    image: linuxserver/kodi-headless
    container_name: kodi
    ports: 
      - '8080:8080'
      - '9090:9090'
      - '9777:9777'
    volumes: 
      - ./conf:/config/.kodi
    restart: always
    environment:
      MYSQL_DB_NAME: kodi
      MYSQL_DB_HOST: db:3306
      MYSQL_DB_USER: kodi
      MYSQL_DB_PASSWORD: kodi

  db:
    image: mariadb:latest
    container_name: mariadb
    volumes: 
      - ./db_data/:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: kodi
      MYSQL_USER: kodi
      MYSQL_PASSWORD: kodi
